In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [19]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [20]:
y=df['Outcome']
X=df.drop(['Outcome'],axis=1)

In [21]:
df.shape

(768, 9)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=30)

**LOGISTIC REGRESSION**

In [23]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(X_train,y_train)
y_pred=reg.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[113,  17],
       [ 24,  38]])

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85       130
           1       0.69      0.61      0.65        62

    accuracy                           0.79       192
   macro avg       0.76      0.74      0.75       192
weighted avg       0.78      0.79      0.78       192



**DECISION TREE**

In [26]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

In [27]:
confusion_matrix(y_test, y_pred)

array([[101,  29],
       [ 27,  35]])

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78       130
           1       0.55      0.56      0.56        62

    accuracy                           0.71       192
   macro avg       0.67      0.67      0.67       192
weighted avg       0.71      0.71      0.71       192



**SVM**

In [29]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test) 

In [30]:
confusion_matrix(y_test, y_pred)

array([[116,  14],
       [ 25,  37]])

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.86       130
           1       0.73      0.60      0.65        62

    accuracy                           0.80       192
   macro avg       0.77      0.74      0.76       192
weighted avg       0.79      0.80      0.79       192



**NAIVE BAYES**

In [32]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test) 

In [33]:
confusion_matrix(y_test, y_pred)

array([[114,  16],
       [ 24,  38]])

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85       130
           1       0.70      0.61      0.66        62

    accuracy                           0.79       192
   macro avg       0.76      0.74      0.75       192
weighted avg       0.79      0.79      0.79       192

