<a href="https://colab.research.google.com/github/hsallrounder/Introduction-to-Machine-Learning-Lab/blob/master/Logistic_Regression_on_Apples_and_Oranges_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
% matplotlib inline

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/apples_and_oranges.csv")
df.head()

Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

**Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.Class=le.fit_transform(df['Class'])
df

Weight  Size  Class
0       69  4.39      1
1       69  4.21      1
2       65  4.09      1
3       72  5.85      0
4       67  4.70      1
5       73  5.68      0
6       70  5.56      0
7       75  5.11      0
8       74  5.36      0
9       65  4.27      1
10      73  5.79      0
11      70  5.47      0
12      74  5.53      0
13      68  4.47      1
14      74  5.22      0
15      65  4.48      1
16      69  4.66      1
17      75  5.25      0
18      67  4.18      1
19      74  5.50      0
20      66  4.13      1
21      70  4.83      1
22      69  4.61      1
23      68  4.08      1
24      67  4.25      1
25      71  5.35      0
26      67  4.01      1
27      70  4.22      1
28      74  5.25      0
29      71  5.26      0
30      73  5.78      0
31      66  4.68      1
32      72  5.72      0
33      73  5.17      0
34      68  4.83      1
35      69  4.11      1
36      69  4.76      1
37      74  5.48      0
38      70  5.59      0
39      73  5.03      0

In [ ]:
y=df['Class']
X=df.drop(['Class'],axis=1)

In [ ]:
df.shape

(40, 3)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

**LOGISTIC REGRESSION**

In [ ]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(X_train,y_train)
y_pred=reg.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[5, 0],
       [0, 5]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



**DECISION TREE**

In [ ]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_pred)

array([[5, 0],
       [0, 5]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test) 

In [ ]:
confusion_matrix(y_test, y_pred)

array([[5, 0],
       [0, 5]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



**NAIVE BAYES**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test) 

In [ ]:
confusion_matrix(y_test, y_pred)

array([[5, 0],
       [0, 5]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

