<a href="https://colab.research.google.com/github/hsallrounder/Introduction-to-Machine-Learning-Lab/blob/master/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy Array
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently 
- NumPy is much faster compare to Python list.

# Difference between NumPy array and Python List

In [ ]:
#python list
%timeit [i**2 for i in range(1,4)]

1.23 µs ± 211 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#NumPy array
import numpy as np
%timeit np.arange(1,4)**2


1.97 µs ± 555 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
#Big size python list
%timeit [i**2 for i in range(1,10000)]

2.93 ms ± 97.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
#NumPy array
%timeit np.arange(1,10000)**2

16.3 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# NumPy array

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.size

4

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(4,)

# Continue

# reshape function()

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#creation of 3D array
arr=np.array([1,2,3,4,5,6,7,8]).reshape(-1,2,2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# zeros(), #ones(), #eye(), #diag() function

In [ ]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([4,5,6,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

# randint() and rand() function

In [ ]:
np.random.randint(1,101,10) # 1 include and 101 exclude

array([40, 27, 51, 58, 97, 87, 50, 38, 15, 64])

In [ ]:
np.random.rand(5) #always takes one argument specify that the total no of elements between 0 and 1

array([0.59088686, 0.12864246, 0.54354114, 0.87775435, 0.80104027])

In [ ]:
np.random.randn(5) # generate nos and hese nos will be normally distributed and if we calulate the mean that will be closer to 0.

array([-0.37682214, -1.47533747,  0.23257858,  2.17527909,  0.55509564])

In [ ]:
arr=np.random.randint(1,111,10).reshape(2,5)
arr

array([[ 14,  11,   4,  60,   7],
       [ 51,  86,  54, 104,  64]])

In [ ]:
arr=np.random.randint(1,111,20)
arr

array([ 99,  82,  68, 104, 103,  94,  58,  18,  14,  54,  43,  61,  34,
        35,   2,  73, 103,  14,  54,  64])

In [ ]:
np.linspace(1,50,5)# distance between each no from its previous one will be equal i.e 12.25

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

# Indexing and Slicing of NumPy array

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
sliced_array=arr[2:4].copy() # index 4 is not included. copy() operation does notv reflect the changes on original  array.
sliced_array

array([3, 4])

In [ ]:
sliced_array[:]=0 #All elements of sliced array will be assigned as 0.
sliced_array

array([0, 0])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[2:]  # starts from index 2 till end.

array([3, 4, 5])

In [ ]:
arr[2:4]

array([3, 4])

In [ ]:
arr[-1:]

array([5])

In [ ]:
arr[-3:]

array([3, 4, 5])

In [ ]:
arr[1:4]

array([2, 3, 4])

In [ ]:
arr[0:5:2] # element of index 0,2,4

array([1, 3, 5])

In [ ]:
#Reversing of an array
arr[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#first 1D array
matrix[0]

array([1, 2, 3])

In [ ]:
matrix[1]

array([4, 5, 6])

In [ ]:
#second element of first 1D array
matrix[0][1]

2

In [ ]:
matrix[1][1]

5

In [ ]:
# Using only single Bracket # it is recommended
matrix[0,1]

2

In [ ]:
matrix[1,1]

5

In [ ]:
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
np.random.seed(123) # it allows to generate same random numbers
arr=np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [ ]:
arr[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [ ]:
arr[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# view vs copy

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
sliced_array=arr[2:4]  
sliced_array

array([3, 4])

In [ ]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [ ]:
arr # view reflect changes in original array

array([1, 2, 0, 0, 5])

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
sliced_array=arr[2:4].copy()
sliced_array

array([3, 4])

In [ ]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [ ]:
arr #Copy does not reflect changes in original array

array([1, 2, 3, 4, 5])

# Conditinal selection

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [ ]:
arr[arr>5]

array([7, 9])

# NumPy axis
for rows put axis=1 and for columns put axis=0

In [ ]:
arr1=np.random.randint(1,10,9).reshape(3,3)
arr1

array([[5, 8, 3],
       [5, 9, 1],
       [8, 4, 5]])

In [ ]:
arr2=np.random.randint(1,10,9).reshape(3,3)
arr2

array([[7, 2, 6],
       [7, 3, 2],
       [9, 4, 6]])

In [ ]:
arr1+arr2

array([[12, 10,  9],
       [12, 12,  3],
       [17,  8, 11]])

In [ ]:
arr1*arr2

array([[35, 16, 18],
       [35, 27,  2],
       [72, 16, 30]])

In [ ]:
arr1.dot(arr2)

array([[118,  46,  64],
       [107,  41,  54],
       [129,  48,  86]])

In [ ]:
np.min(arr)

0

In [ ]:
# calculate min element rowwise
np.min(arr1,axis=1)

array([3, 1, 4])

In [ ]:
# calcilate max element columnwise
np.max(arr1, axis=0)

array([8, 9, 5])

# hstack() and vstack() function
these are used to concatinate two matrices horizontally and vertically

In [ ]:
matrix1=np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[1, 3, 7],
       [3, 5, 5],
       [7, 4, 1]])

In [ ]:
matrix2=np.random.randint(50,100,9).reshape(3,3)
matrix2

array([[56, 64, 89],
       [61, 57, 51],
       [93, 87, 75]])

In [ ]:
np.hstack((matrix1,matrix2))

array([[ 1,  3,  7, 56, 64, 89],
       [ 3,  5,  5, 61, 57, 51],
       [ 7,  4,  1, 93, 87, 75]])

In [ ]:
np.vstack((matrix1,matrix2))

array([[ 1,  3,  7],
       [ 3,  5,  5],
       [ 7,  4,  1],
       [56, 64, 89],
       [61, 57, 51],
       [93, 87, 75]])